services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapi
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "80:8080"

  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-tests
    profiles:
      - tests
    container_name: tests
    entrypoint: ["dotnet", "test", "/tests/webapi.Tests.csproj"]
    depends_on:
      - webapi

volumes:
  db-data:
